### ISSUE TITLE
Ready to help with the project, please share details. 

### ISSUE THREAD

**Issue by narendraj9** [degree9/covenant#1]
Hi, 

I am planning to implement an attribute-based access control system for a web service at work. I was exploring options in Clojure and came across your repository. Has there been any progress on this? Do you need help? Please share any design thoughts or plans that you have.

**Comment by flyboarder** [comment]
Yes there is some basic work on this, will be build with Clojure Spec. https://medium.com/degree9/data-validation-schema-spec-5547e33596bd

**Comment by flyboarder** [comment]
[Access Control](https://onury.io/accesscontrol/) is a great example for a related api.

**Comment by flyboarder** [comment]
@narendraj9 initial works are now underway
